enum Actions {
  ADD_FILTER = 'ADD_FILTER',
  REMOVE_FILTER = 'REMOVE_FILTER',
  CLEAR_FILTERS = 'CLEAR_FILTERS',
  UPDATE_FILTER = 'UPDATE_FILTER',
  REMOVE_FILTER_OPTION = 'REMOVE_OPTION',
  UPDATE_FILTER_OPTION = 'UPDATE_FILTER_OPTION',
}

export default Actions;
